apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sql-example
  labels:
    app: sql-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sql-example
    spec:
      containers:
      - name: sql-example
        imagePullPolicy: Always
        image: ${IMAGE_NAME}:${TAG}
        ports:
          - containerPort: 3000
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.14
        command: ["/cloud_sql_proxy",
                    "-instances=${INSTANCE_CONNECTION_NAME}=tcp:3306",
                    "-credential_file=/secrets/cloudsql/sql-admin.json"]
        securityContext:
          runAsUser: 2  
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
---
kind: Service
apiVersion: v1
metadata:
  name: sql-example
spec:
  type: LoadBalancer
  selector:
    app: sql-example
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
